#!/bin/sh
# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/config/xprofile
# because that file is run automatically if someone uses a display manager (login screen)
# and so they are needed there. To prevent doubling up commands, I
# source them here with the line below.

. $XDG_CONFIG_HOME/x11/xprofile

# Your default Windoe Manager is determined in your `~/.profile` on login.  Here we
# run the proper command to run when the graphical environment starts.

# Comment/uncomment these lines depending on what wm you want to use. Also
# check the i3blocks line above.
# ssh-agent dwm
# ssh-agent i3

export USERXSESSION="$XDG_CACHE_HOME/x11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/x11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/x11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"

. ~/.config/x11/keymaps

#exec startxfce4
exec awesome
# exec alacritty
